import { ClipboardCheck, FileText, FolderKanban, Search, X } from 'lucide-react';
import { useEffect, useRef, useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { api } from '../services/api';
import type { SearchResults } from '../types';

const empty: SearchResults = { projects: [], tasks: [], documents: [] };

export function GlobalSearch({ open, onClose }: { open: boolean; onClose: () => void }) {
  const navigate = useNavigate(); const inputRef = useRef<HTMLInputElement>(null); const [query, setQuery] = useState(''); const [results, setResults] = useState(empty); const [loading, setLoading] = useState(false); const [active, setActive] = useState(0);
  const items = [...results.projects.map((item) => ({ id: `p-${item.id}`, label: item.name, meta: `${item.city} · Projekt`, to: `/projects/${item.id}`, icon: FolderKanban })), ...results.tasks.map((item) => ({ id: `t-${item.id}`, label: item.title, meta: `${item.project?.name ?? 'Projekt'} · Aufgabe`, to: `/projects/${item.projectId}`, icon: ClipboardCheck })), ...results.documents.map((item) => ({ id: `d-${item.id}`, label: item.name, meta: `${item.project.name} · Dokument`, to: `/documents?project=${item.projectId}`, icon: FileText }))];
  useEffect(() => { if (!open) return; inputRef.current?.focus(); setQuery(''); setResults(empty); setActive(0); }, [open]);
  useEffect(() => { if (!open || query.trim().length < 2) { setResults(empty); return; } const controller = new AbortController(); const timer = window.setTimeout(async () => { setLoading(true); try { setResults(await api.search(query)); setActive(0); } catch { if (!controller.signal.aborted) setResults(empty); } finally { if (!controller.signal.aborted) setLoading(false); } }, 250); return () => { controller.abort(); window.clearTimeout(timer); }; }, [query, open]);
  if (!open) return null;
  const select = (to: string) => { navigate(to); onClose(); };
  return <div className="command-backdrop" role="presentation" onMouseDown={(event) => event.target === event.currentTarget && onClose()}><section className="command-palette" role="dialog" aria-modal="true" aria-label="Globale Suche"><div className="command-input"><Search /><input ref={inputRef} value={query} onChange={(event) => setQuery(event.target.value)} onKeyDown={(event) => { if (event.key === 'Escape') onClose(); if (event.key === 'ArrowDown') { event.preventDefault(); setActive((value) => Math.min(items.length - 1, value + 1)); } if (event.key === 'ArrowUp') { event.preventDefault(); setActive((value) => Math.max(0, value - 1)); } if (event.key === 'Enter' && items[active]) select(items[active].to); }} placeholder="Projekte, Aufgaben und Dokumente suchen …" aria-activedescendant={items[active]?.id} /><button className="icon-button" onClick={onClose} aria-label="Suche schließen"><X /></button></div><div className="command-results" role="listbox">{query.trim().length < 2 ? <div className="command-hint"><kbd>⌘/Ctrl</kbd><kbd>K</kbd><span>Tippe mindestens zwei Zeichen.</span></div> : loading ? <div className="command-empty">Suche läuft …</div> : items.length ? items.map(({ id, label, meta, to, icon: Icon }, index) => <button id={id} key={id} role="option" aria-selected={index === active} className={index === active ? 'command-result command-result--active' : 'command-result'} onMouseEnter={() => setActive(index)} onClick={() => select(to)}><span><Icon /></span><div><strong>{label}</strong><small>{meta}</small></div><kbd>↵</kbd></button>) : <div className="command-empty">Keine passenden Ergebnisse gefunden.</div>}</div></section></div>;
}
