import { Eye, EyeOff, LoaderCircle, LockKeyhole, Mail } from 'lucide-react';
import { useState, type FormEvent } from 'react';
import { Link, useLocation, useNavigate } from 'react-router-dom';
import { useAuth } from '../auth/AuthContext';
import { AuthShell } from '../components/AuthShell';

export function LoginPage() {
  const { login } = useAuth(); const navigate = useNavigate(); const location = useLocation();
  const [email, setEmail] = useState(''); const [password, setPassword] = useState(''); const [showPassword, setShowPassword] = useState(false); const [remember, setRemember] = useState(true); const [error, setError] = useState<string | null>(null); const [submitting, setSubmitting] = useState(false);
  const submit = async (event: FormEvent) => { event.preventDefault(); setError(null); if (!email || !password) return setError('Bitte gib E-Mail-Adresse und Passwort ein.'); setSubmitting(true); try { await login({ email, password }); const from = (location.state as { from?: string } | null)?.from; navigate(from ?? '/dashboard', { replace: true }); } catch (reason) { setError(reason instanceof Error ? reason.message : 'Anmeldung fehlgeschlagen.'); } finally { setSubmitting(false); } };
  return <AuthShell eyebrow="MeterFlow Workspace" title="Willkommen zurück" subtitle="Melde dich an, um deine Mieterstrom-Projekte zu verwalten."><form className="auth-form" onSubmit={submit}>{error && <div className="auth-error">{error}</div>}<label className="auth-field"><span>E-Mail-Adresse</span><div><Mail /><input type="email" value={email} onChange={(event) => setEmail(event.target.value)} placeholder="name@unternehmen.de" autoComplete="email" autoFocus /></div></label><label className="auth-field"><span>Passwort</span><div><LockKeyhole /><input type={showPassword ? 'text' : 'password'} value={password} onChange={(event) => setPassword(event.target.value)} placeholder="Mindestens 8 Zeichen" autoComplete="current-password" /><button type="button" onClick={() => setShowPassword((value) => !value)} aria-label={showPassword ? 'Passwort verbergen' : 'Passwort anzeigen'}>{showPassword ? <EyeOff /> : <Eye />}</button></div></label><label className="remember-row"><input type="checkbox" checked={remember} onChange={(event) => setRemember(event.target.checked)} /> <span>Angemeldet bleiben</span></label><button className="auth-submit" disabled={submitting}>{submitting && <LoaderCircle />}{submitting ? 'Anmeldung läuft …' : 'Anmelden'}</button><p className="auth-switch">Noch kein Konto? <Link to="/register">Jetzt registrieren</Link></p></form></AuthShell>;
}
