import { Eye, EyeOff, LoaderCircle, LockKeyhole, Mail, UserRound } from 'lucide-react';
import { useState, type FormEvent } from 'react';
import { Link, useNavigate } from 'react-router-dom';
import { useAuth } from '../auth/AuthContext';
import { AuthShell } from '../components/AuthShell';
import { useToast } from '../components/Toast';

export function RegisterPage() {
  const { register } = useAuth(); const navigate = useNavigate(); const { showToast } = useToast();
  const [values, setValues] = useState({ firstName: '', lastName: '', email: '', password: '', confirmation: '' }); const [showPassword, setShowPassword] = useState(false); const [error, setError] = useState<string | null>(null); const [submitting, setSubmitting] = useState(false);
  const setField = (field: keyof typeof values, value: string) => setValues((current) => ({ ...current, [field]: value }));
  const submit = async (event: FormEvent) => { event.preventDefault(); setError(null); if (!values.firstName.trim() || !values.lastName.trim() || !values.email || !values.password) return setError('Bitte fülle alle Pflichtfelder aus.'); if (values.password.length < 8) return setError('Das Passwort muss mindestens 8 Zeichen lang sein.'); if (values.password !== values.confirmation) return setError('Die Passwörter stimmen nicht überein.'); setSubmitting(true); try { await register({ firstName: values.firstName.trim(), lastName: values.lastName.trim(), email: values.email, password: values.password }); showToast('Konto erfolgreich erstellt.'); navigate('/dashboard', { replace: true }); } catch (reason) { setError(reason instanceof Error ? reason.message : 'Registrierung fehlgeschlagen.'); } finally { setSubmitting(false); } };
  return <AuthShell eyebrow="Konto erstellen" title="Starte mit MeterFlow." subtitle="Erstelle deinen Zugang und verwalte Mieterstrom-Projekte zentral."><form className="auth-form" onSubmit={submit}>{error && <div className="auth-error">{error}</div>}<div className="auth-name-grid"><label className="auth-field"><span>Vorname</span><div><UserRound /><input value={values.firstName} onChange={(event) => setField('firstName', event.target.value)} placeholder="Vorname" autoComplete="given-name" autoFocus /></div></label><label className="auth-field"><span>Nachname</span><div><UserRound /><input value={values.lastName} onChange={(event) => setField('lastName', event.target.value)} placeholder="Nachname" autoComplete="family-name" /></div></label></div><label className="auth-field"><span>E-Mail-Adresse</span><div><Mail /><input type="email" value={values.email} onChange={(event) => setField('email', event.target.value)} placeholder="name@unternehmen.de" autoComplete="email" /></div></label><label className="auth-field"><span>Passwort</span><div><LockKeyhole /><input type={showPassword ? 'text' : 'password'} value={values.password} onChange={(event) => setField('password', event.target.value)} placeholder="Mindestens 8 Zeichen" autoComplete="new-password" /><button type="button" onClick={() => setShowPassword((value) => !value)} aria-label={showPassword ? 'Passwort verbergen' : 'Passwort anzeigen'}>{showPassword ? <EyeOff /> : <Eye />}</button></div></label><label className="auth-field"><span>Passwort bestätigen</span><div><LockKeyhole /><input type={showPassword ? 'text' : 'password'} value={values.confirmation} onChange={(event) => setField('confirmation', event.target.value)} placeholder="Passwort wiederholen" autoComplete="new-password" /></div></label><button className="auth-submit" disabled={submitting}>{submitting && <LoaderCircle />}{submitting ? 'Konto wird erstellt …' : 'Konto erstellen'}</button><p className="auth-switch">Bereits registriert? <Link to="/login">Zur Anmeldung</Link></p></form></AuthShell>;
}
